#!/usr/bin/env bash
# http://andxyz.com personal aliases

### ls
alias ls="ls -F"
alias ll="ls -l"
alias la='ls -A'

### personal ~/bin
alias addr='nocorrect addr'

### andxyz random
##### a sublimetext github.com/bkeepers tip
alias e="subl -n ./"
alias hhistory='history -99999 | cut -c 8-'
##### the only advantage cmd.exe has
alias cls='clear'
##### remember to brew install coreutils see
alias ls='gls --color'
alias pps="ps auwwx | perl -p -e 's/\n/\n\n/'"
alias httpheader="http --header get"

## Mac OSX
alias sscreensaver='/System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine'
alias pports='sudo lsof -Pni4 | grep LISTEN'

#### htop
alias hhtop="htop --sort-key Command"
alias hhtopcommand="htop --sort-key Command"
alias hhtopcpu="htop --sort-key PERCENT_CPU"
alias hhtopmem="htop --sort-key PERCENT_MEM"
alias hhtoppid="htop --sort-key PID"

### git
alias gg='git grep --break --heading --line-number'
alias gball='git branch --all --verbose'
alias gbb='git branch-list-by-date.sh'
alias gb='git branch --list --verbose'
alias gs='git status --short --branch'
alias gco='git checkout'

### rails and ruby
## alias bi="bundle install --binstubs --without=production"
alias bi='bundle check || bundle install'
alias be='bundle exec'
alias ttail='tail -f log/development.log'
alias serve="ruby -run -e httpd -- -p 8000 ."
### ruby rails zsh settings
if which noglob >/dev/null; then
  : # This is the shell equivalent of a "NOP"
  # alias bundle='nocorrect bundle'
  # alias rake='nocorrect rake' # allows square brackets for rake task invocation
fi

### node
alias ni='npm install --silent >> /dev/null 2>&1'
### node zsh settings
# if which noglob >/dev/null; then
#   alias bower='nocorrect bower'
#   alias grunt='nocorrect grunt' # troubles? try `npm install -g npm &&  npm install -g grunt-cli`
#   alias npm='nocorrect npm'
#   alias node='nocorrect node'
# fi

### tools
alias mmitmproxy='mitmproxy --palette solarized_light'
alias jqbrowser="jq '.' > /tmp/tmp.json && open -b 'com.google.chrome' /tmp/tmp.json"

### zsh correction headaches
if which noglob >/dev/null; then
  #### homebrew
  alias brew='nocorrect brew'
  #### java
  alias jenv='nocorrect jenv'
fi

## webservers
### tips thanks to http://blog.frd.mn/install-nginx-php-fpm-mysql-and-phpmyadmin-on-os-x-mavericks-using-homebrew/
###
### nginx
### `sudo find /usr/local -iname homebrew.*plist`
### `ln -sfv /usr/local/Cellar/nginx/1.4.6/homebrew.mxcl.nginx.plist ~/Library/LaunchAgents/
### `chmod 644 /usr/local/bin/nginx && chown root /usr/local/bin/nginx`
alias nginx.start='sudo launchctl load ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist'
alias nginx.stop='sudo launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist'
alias nginx.restart='nginx.stop && nginx.start'

### mysql
alias mysql.start="launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist"
alias mysql.stop="launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist"
alias mysql.restart='mysql.stop && mysql.start'

### nginx logs
alias nginx.logs.error='tail -250f /usr/local/etc/nginx/logs/error.log'
alias nginx.logs.access='tail -250f /usr/local/etc/nginx/logs/access.log'
alias nginx.logs.default.access='tail -250f /usr/local/etc/nginx/logs/default.access.log'
alias nginx.logs.default-ssl.access='tail -250f /usr/local/etc/nginx/logs/default-ssl.access.log'
alias nginx.logs.phpmyadmin.error='tail -250f /usr/local/etc/nginx/logs/phpmyadmin.error.log'
alias nginx.logs.phpmyadmin.access='tail -250f /usr/local/etc/nginx/logs/phpmyadmin.access.log'

### php55
alias php-fpm55.wat="cat ~/Library/LaunchAgents/homebrew.mxcl.php55.plist"
alias php-fpm55.start="launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.php55.plist"
alias php-fpm55.stop="launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.php55.plist"
alias php-fpm55.restart='php55-fpm.stop && php55-fpm.start'

### php54
alias php-fpm54.wat="cat ~/Library/LaunchAgents/homebrew-php.josegonzalez.php54.plist"
alias php-fpm54.start="launchctl load -w ~/Library/LaunchAgents/homebrew-php.josegonzalez.php54.plist"
alias php-fpm54.stop="launchctl unload -w ~/Library/LaunchAgents/homebrew-php.josegonzalez.php54.plist"
alias php-fpm54.restart='php54-fpm.stop && php54-fpm.start'
### generic
alias php-fpm.killall='pgrep php-fpm | xargs kill -9'

## silly stuff

### test internet with speedtest
##### python peeps checkout https://github.com/sivel/speedtest-cli
##### tips thanks to http://fauxzen.com/speedtest-from-the-cli/
alias sspeedtest='echo "scale=2; `curl  --progress-bar -w "%{speed_download}" http://cachefly.cachefly.net/10mb.test -o test.zip ` / 131072" | bc | xargs -I {} echo {}Mb\/s && rm -rf test.zip'

## top ten used commands line tools
alias ttopten='ttopten() { fc -l -n 1 | cut -d" " -f1-1 | gsort | guniq -c | gsort -rn | ghead -10 }; ttopten;'
alias ttopten1="history -99999 | gawk '{print $2}' | gsort | guniq -c | gsort -rn | ghead -20"
alias ttopten2="fc -l -n 1 | gsort | guniq -c | gsort -rn | ghead -20"
alias ttopten3="history -99999 | gtr -s ' ' | gcut -d' ' -f3- | gsort | guniq -c | gsort -rn | ghead -20"
alias ttopten_maryan_bash='f() { history|cut -d\  -f4-5|sort|uniq -c|sort -rn|head -${1:-30}; }; f'
