#!/usr/bin/env bash
# http://andxyz.com personal aliases

### ls
### Colorize the ls output
alias ls="ls -F -h --group-directories-first --color=auto"
alias ll="ls -l -h --group-directories-first --color=auto"
alias la="ls -A -h --group-directories-first --color=auto"

### send to the trashbin not into the ether
# alias rm='rmtrash'

### personal ~/bin
alias addr='nocorrect addr'

### andxyz random
alias hhistory='history -99999 | cut -c 8-'
##### the only advantage cmd.exe has
alias cls='clear'
##### remember to brew install coreutils see brew_install_stuff.s
alias pps="ps auwwx | perl -p -e 's/\n/\n\n/'"
alias hhttpheader="http --header get"

## Mac OSX
alias sscreensaver='/System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine'
alias eespresso='caffeinate -disu -w 1'
alias ddouble_rainbow.sh='double_rainbow.sh'

## debug
# Lone Star Ruby Conference 2010 - Debugging Ruby by Aman Gupta
# https://www.youtube.com/watch?v=gEMnwRAUlKE
alias pports='sudo lsof -Pni4 | grep LISTEN'
alias llsof='sudo lsof -nP'

#### htop
alias hhtop="htop --sort-key Command"
alias hhtopcommand="htop --sort-key Command"
alias hhtopcpu="htop --sort-key PERCENT_CPU"
alias hhtopmem="htop --sort-key PERCENT_MEM"
alias hhtoppid="htop --sort-key PID"

## git aliases
alias gs='git status --short --branch' # fucking ghostscript
alias gss='git status --branch --find-renames'
alias gco='git checkout'


## codes
alias cctags='cctags.sh &'
alias zz='cd $(find ~/wonolo/* -maxdepth 0 -type d | fzf --preview "git -C {} status --short --branch")'

### rails and ruby
## alias bi="bundle install --binstubs"
alias bi='bundle check || bundle install'
alias be='bundle exec'
alias wwebserve="ruby -run -e httpd -- -p 8000 ."

### ruby rails zsh settings
if which noglob >>/dev/null; then
  : # This is the shell equivalent of a "NOP"
  # alias bundle='nocorrect bundle'
  # alias rake='nocorrect rake' # allows square brackets for rake task invocation
fi

### node
# alias ni='npm install --silent >> /dev/null 2>&1'
alias yi='yarn check || yarn install'
### node zsh nocorrect headaches
# if which noglob >/dev/null; then
#   alias bower='yarn run bower'
#   alias ember='nocorrect ember'
#   alias grunt='yarn run grunt'
#   alias gulp='yarn run gulp'
#   alias npm='nocorrect npm'
#   alias node='nocorrect node'
# fi

### tools
alias mmitmproxy='mitmproxy --palette solarized_light'

### zsh correction headaches
if which noglob >/dev/null; then
  #### homebrew
  alias brew='nocorrect brew'
fi

## webservers
### tips thanks to http://blog.frd.mn/install-nginx-php-fpm-mysql-and-phpmyadmin-on-os-x-mavericks-using-homebrew/
###
### nginx
### `sudo find /usr/local -iname homebrew.*plist`
### `ln -sfv /usr/local/Cellar/nginx/1.4.6/homebrew.mxcl.nginx.plist ~/Library/LaunchAgents/
### `chmod 644 /usr/local/bin/nginx && chown root /usr/local/bin/nginx`
alias nnginx.start='sudo launchctl load ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist'
alias nnginx.stop='sudo launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist'
alias nnginx.restart='nginx.stop && nginx.start'

### mysql
alias mmysql.start="launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist"
alias mmysql.stop="launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist"
alias mmysql.restart='mysql.stop && mysql.start'

### nginx logs
alias nnginx.logs.error='tail -250f /usr/local/etc/nginx/logs/error.log'
alias nnginx.logs.access='tail -250f /usr/local/etc/nginx/logs/access.log'
alias nnginx.logs.default.access='tail -250f /usr/local/etc/nginx/logs/default.access.log'
alias nnginx.logs.default-ssl.access='tail -250f /usr/local/etc/nginx/logs/default-ssl.access.log'
alias nnginx.logs.phpmyadmin.error='tail -250f /usr/local/etc/nginx/logs/phpmyadmin.error.log'
alias nnginx.logs.phpmyadmin.access='tail -250f /usr/local/etc/nginx/logs/phpmyadmin.access.log'

### php56
alias pphpfpm56.wat="cat ~/Library/LaunchAgents/homebrew-php.php56.plist"
alias pphpfpm56.start="brew services start phpfpm56"
alias pphpfpm56.stop="launchctl unload -w ~/Library/LaunchAgents/homebrew-php.php56.plist"
alias pphpfpm56.restart='pphp56fpm.stop && pphp56fpm.start'

### generic
alias pphpfpm.killall='pgrep php-fpm | xargs kill -9'

## silly stuff

### test internet with speedtest
##### python peeps checkout https://github.com/sivel/speedtest-cli
##### tips thanks to http://fauxzen.com/speedtest-from-the-cli/
alias sspeedtest='echo "scale=2; `curl  --progress-bar -w "%{speed_download}" http://cachefly.cachefly.net/10mb.test -o test.zip ` / 131072" | bc | xargs -I {} echo {}Mb\/s && rm -rf test.zip'

## top ten used commands line tools
# remember to try git churn from time to time
alias ttopten='ttopten() { fc -l -n 1 | cut -d" " -f1-1 | gsort | guniq -c | gsort -rn | ghead -10 }; ttopten;'
alias ttopten1="history -99999 | gawk '{print $2}' | gsort | guniq -c | gsort -rn | ghead -20"
alias ttopten2="fc -l -n 1 | gsort | guniq -c | gsort -rn | ghead -20"
alias ttopten3="history -99999 | gtr -s ' ' | gcut -d' ' -f3- | gsort | guniq -c | gsort -rn | ghead -20"
alias ttopten_maryan_bash='f() { history|cut -d\  -f4-5|sort|uniq -c|sort -rn|head -${1:-30}; }; f'
