#!/usr/bin/env bash

# unset SSH_AUTH_SOCK && unset SSH_AGENT_PID
#
## homebrew solution to using homebrew "ssh-agent"
### more info here https://www.stormacq.com/mac-os-x-makes-handling-ssh-keys-easier/
#
# launchctl unload /System/Library/LaunchAgents/org.openbsd.ssh-agent.plist
# brew install openssh --with-brewed-openssl --with-keychain-support
# brew install Caskroom/cask/lunchy --force
# lunchy scan /usr/local/Cellar
# lunchy list
# lunchy install /System/Library/LaunchAgents/org.openbsd.ssh-agent.plist
#
lunchy start org.openbsd.ssh-agent > /dev/null 2>&1
unset SSH_AUTH_SOCK
unset SSH_AGENT_PID

## test my ssh-agent setup with github
# unset SSH_AUTH_SOCK
# unset SSH_AGENT_PID
# export -- SSH_AUTH_SOCK=$(launchctl getenv SSH_AUTH_SOCK)
# ssh -Tv git@github.com

## old solution
## http://www.dctrwatson.com/2013/07/how-to-update-openssh-on-mac-os-x/
## http://superuser.com/questions/141044/sharing-the-same-ssh-agent-among-multiple-login-sessions
## ssh_agent_tricks() {
##     eval "$(brew --prefix)/bin/ssh-agent"
##     unset SSH_AUTH_SOCK
##     export -- SSH_AUTH_SOCK=$(launchctl getenv SSH_AUTH_SOCK)
## }
#
## ssh_agent_tricks
#
## function cleanup_openssh {
##   echo "Killing SSH-Agent"
##   kill -9 $SSH_AGENT_PID
## }
#
#
## trap cleanup_openssh EXIT
#