#!/usr/bin/env bash
# echo 'fuck that you have new mail shit'
unset MAILCHECK
test -f "$HOME/.hushlogin" &&
touch $HOME/.hushlogin

# disable the fucking core dumps
ulimit -S -c 0

# echo 'use sublimetext3 (with '-w' wait for close of file) as default editor'
# http://unix.stackexchange.com/questions/4859/visual-vs-editor-whats-the-difference
# http://stackoverflow.com/questions/8299610/zsh-command-not-found-for-editor
# ~/ $ cat ~/bin/EDITOR
# #!/bin/sh
# #open -Wn -- "$@"
# subl -w -- "$@"
export -- EDITOR="$HOME/bin/EDITOR"
export -- VISUAL="$HOME/bin/EDITOR"

# echo 'give me history you dogs of history'
HISTFILE=$HOME/.history
HISTSIZE=9999
SAVEHIST=999999

# print elapsed time when more than 10 seconds
REPORTTIME=10

# homebrew "open ssh-agent"
eval $(ssh-agent) 2>&1 > /dev/null

function cleanup_openssh {
  echo "Killing SSH-Agent"
  kill -9 $SSH_AGENT_PID
}

trap cleanup_openssh EXIT
