#!/usr/bin/env bash
# echo 'fuck that you have new mail shit'
unset MAILCHECK
test -f "${HOME}/.hushlogin" && touch "${HOME}/.hushlogin"

# disable the fucking core dumps
ulimit -S -c 0

# echo 'use sublimetext3 (with '-w' wait for close of file) as default editor'
# http://unix.stackexchange.com/questions/4859/visual-vs-editor-whats-the-difference
# http://stackoverflow.com/questions/8299610/zsh-command-not-found-for-editor
# ~/ $ cat ~/bin/EDITOR
# #!/bin/sh
# #open -Wn -- "$@"
# subl -w -- "$@"
export -- EDITOR="subl -w -n -- ${*}"
export -- EDITOR_USING_CURRENT_PROJECT="subl -- ${*}"
export -- PAGER="less -R"
export -- VISUAL="${EDITOR}"

# echo 'give me history you dogs of history'
export -- HISTFILE=$HOME/.history
export -- HISTSIZE=999999
export -- SAVEHIST=999999

# print elapsed time when more than 10 seconds
export -- REPORTTIME=10

export -- LESSSECURE=1 # seems legit
export -- HOMEBREW_NO_AUTO_UPDATE=1 # sounds good to me

# ruby hacks, https://github.com/rails/rails/issues/38560
export -- OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
export -- DISABLE_SPRING=true

# [ -n "$PS1" ] && source "$HOME/code/git/base16-shell/scripts/base16-default-dark.sh" # colors

# brew info z
# shellcheck source=/usr/local/etc/profile.d/z.sh
source /usr/local/etc/profile.d/z.sh

# use the homebrew git prompt script else use and old one
if test -f /usr/local/etc/bash_completion.d/git-prompt.sh; then
  # shellcheck source=/usr/local/etc/bash_completion.d/git-prompt.sh
  source /usr/local/etc/bash_completion.d/git-prompt.sh
else
  # shellcheck source="${HOME}"/.shell/git-prompt.sh
  source "${HOME}"/.shell/git-prompt.sh
fi

if test -f /usr/local/etc/gh_completion; then
  source /usr/local/etc/gh_completion
fi
