#!/usr/bin/env bash
# echo 'fuck that you have new mail shit'
unset MAILCHECK
test -f "$HOME/.hushlogin" &&
touch $HOME/.hushlogin

# disable the fucking core dumps
ulimit -S -c 0

# echo 'use sublimetext3 as default editor'
export EDITOR='subl -w'

# echo 'give me history you dogs of history'
HISTFILE=$HOME/.history
HISTSIZE=9999
SAVEHIST=999999

# print elapsed time when more than 10 seconds
REPORTTIME=10

# homebrew openssh
eval $(ssh-agent)

function cleanup_openssh {
  echo "Killing SSH-Agent"
  kill -9 $SSH_AGENT_PID
}

trap cleanup_openssh EXIT
