#!/usr/bin/env bash

## using homebrew "ssh-agent"
## more info here https://www.packetmischief.ca/2016/09/06/ssh-agent-on-os-x/
#
# brew install openssl
# brew info openssh
# brew install openssh
# brew cask install lunchy --force
# lunchy scan ~/Library/LaunchAgents
# lunchy list

# subl ~/Library/LaunchAgents/org.homebrew.ssh-agent.plist
# launchctl load ~/Library/LaunchAgents/org.homebrew.ssh-agent.plist
# launchctl list | grep 'ssh-agent'

# when it works
# srw------- 1 andxyz staff 0 Mar  1 16:45 /Users/andxyz/.ssh-agent.sock

## test setup with github
test_my_ssh_agent() {
  unset SSH_AUTH_SOCK
  unset SSH_AGENT_PID
  export -- SSH_AUTH_SOCK="$HOME/.ssh-agent.sock"
  ssh -V
  $(find /usr/local/Cellar/openssl -name 'openssl' -type f) version
  /usr/local/bin/ssh-add ~/.ssh/andxyz-github
  ssh-add -l
  ssh -Tv git@github.com
  launchctl list | grep -i 'ssh-agent'
}
## "Hi andxyz! You've successfully authenticated, but GitHub does not provide shell access"

## old solutions
## http://www.dctrwatson.com/2013/07/how-to-update-openssh-on-mac-os-x/
## http://superuser.com/questions/141044/sharing-the-same-ssh-agent-among-multiple-login-sessions

## other notes
## http://rabexc.org/posts/pitfalls-of-ssh-agents

use_brew_ssh_agent_setup() {
  unset SSH_AUTH_SOCK
  unset SSH_AGENT_PID
  export SSH_AUTH_SOCK="$HOME/.ssh-agent.sock"
  lunchy start org.homebrew.ssh-agent > /dev/null 2>&1
  lunchy status org.homebrew.ssh-agent
}

use_osx_ssh_agent_setup() {
  export SSH_AUTH_SOCK=$(launchctl getenv SSH_AUTH_SOCK)
  export SSH_AGENT_PID=$(launchctl getenv SSH_AGENT_PID)
  launchctl start org.openbsd.ssh-agent
  /usr/bin/ssh-add ~/.ssh/andxyz-github || true
  /usr/bin/ssh-add ~/.ssh/work || true
  /usr/bin/ssh-add -l
}

use_osx_ssh_agent_setup
