#!/usr/bin/env bash
# echo 'fuck that you have new mail shit'
unset MAILCHECK
test -f "$HOME/.hushlogin" &&
touch $HOME/.hushlogin

# disable the fucking core dumps
ulimit -S -c 0

# echo 'use sublimetext3 (with '-w' wait for close of file) as default editor'
# http://unix.stackexchange.com/questions/4859/visual-vs-editor-whats-the-difference
# http://stackoverflow.com/questions/8299610/zsh-command-not-found-for-editor
# ~/ $ cat ~/bin/EDITOR
# #!/bin/sh
# #open -Wn -- "$@"
# subl -w -- "$@"
export -- EDITOR="subl -w -n -- ${@}"
export -- EDITOR_USING_CURRENT_PROJECT="subl -- ${@}"
export -- PAGER="less -R"
export -- VISUAL="${EDITOR}"

# echo 'give me history you dogs of history'
export -- HISTFILE=$HOME/.history
export -- HISTSIZE=999999
export -- SAVEHIST=999999

# print elapsed time when more than 10 seconds
export -- REPORTTIME=10

export -- LESSSECURE=1 # seems legit

# [ -n "$PS1" ] && source "$HOME/code/_clone/base16-shell/scripts/base16-default-dark.sh" # colors

## disable for now, not enough tips :D
# Displays a random tip from the .tips directory when opening the shell
# Requires gshuf (brew install coreutils)
# (
#   TIP_PATH=$(find ~/.tips -type f -name tips.txt | gshuf -n1)    # Pick a random tips.txt file
#   TIP_TILE=${TIP_PATH#"$HOME/.tips/"}                            # i.e., ~/.tips/vim/vanilla/tips.txt  --->  vim/vanilla/tips.txt
#   echo "From ${TIP_TILE%.txt}:"                                  # i.e., "From vim/vanilla/tips:"
#   gshuf -n1 < "$TIP_PATH"                                        # Displays a random line from the tip file
# )
