#!/usr/bin/env bash

function httpless {
    # `httpless example.org'
    http --pretty=all --print=HBhb "$@" | less -R;
}

function sscreencapture-in-2-seconds-send-to-desktop {
  screencapture -T2 -S -x "$HOME/Desktop/screenshot-$(date +%Y-%m-%d__%H_%M_%S).png"
}

function postgresstart {
  local pidfile="/usr/local/var/postgres/postmaster.pid"
  if [ -s $pidfile ] && kill -0 $(cat $pidfile | head -n 1) > /dev/null 2>&1; then
    echo "Already running"
  else
    pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
  fi
}

function postgresstop {
  pg_ctl -D /usr/local/var/postgres stop
}

function mongoose-http-server {
  local port=${1:-8000}
  local ip=$(ipconfig getifaddr en0)
  echo "Serving on ${ip}:${port} ..."
  python -m SimpleHTTPServer ${port}
}

# https://github.com/aykamko/tag
export -- TAG_CMD_FMT_STRING="${EDITOR_USING_CURRENT_PROJECT} {{.Filename}}:{{.LineNumber}}"
if (( $+commands[tag] )); then
  function tag() { command tag --ignore-dir './log' --ignore-dir './vendor' --ignore-dir './tmp' "${@}"; source ${TAG_ALIAS_FILE:-/tmp/tag_aliases} 2>/dev/null }
  alias ag=tag
fi
