#!/usr/bin/env bash
## andxyz path stuff
export -- PATH="$HOME/bin:/usr/local/sbin:/usr/local/bin:$PATH"
export -- MANPATH="/usr/local/share/man:$MANPATH"
export -- MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# autoenv stuff
# brew info autoenv
test -f "/usr/local/opt/autoenv/activate.sh" &&
source /usr/local/opt/autoenv/activate.sh

# subversion stuff
# brew info subversion
test -d "$PATH:/opt/subversion/bin" &&
export -- PATH="$PATH:/opt/subversion/bin"

### language setup stuff

# android sdk magic
export -- ANDROID_HOME=/Applications/android-sdk-macosx/
export -- STUDIO_JDK=/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk
test -d "/Applications/android-sdk-macosx/platform-tools" &&
export -- PATH="$PATH:/Applications/android-sdk-macosx/platform-tools"
test -d "/Applications/android-sdk-macosx/tools" &&
export -- PATH="$PATH:/Applications/android-sdk-macosx/tools"
test -d "/Applications/android-sdk-macosx/" &&

# golang https://golang.org/doc/install or `brew install go`
export -- PATH=$PATH:/usr/local/go/bin
export -- GOPATH=$HOME/code/gowork
## Note: GOROOT must be set only when installing to a custom location.
#export GOROOT=$HOME/go
#export PATH=$PATH:$GOROOT/bin


# haskell uses cabal
test -d "$HOME/.cabal/bin" &&
export -- PATH="$HOME/.cabal/bin:$PATH"

# nodejs - creationix node version management (nvm)
test -f "$HOME/.nvm/nvm.sh"
source $HOME/.nvm/nvm.sh
# example nvm commands (because I always forget)
# nvm ls-remote
# nvm install v4.1.0
# nvm alias default v4.1.0
# nvm use v4.1.0
#
# export some NODE vars
# export -- NODE_PATH="$NVM_PATH"
# export -- NODE_BIN="$NVM_BIN"

# add local npm packages to path
export -- PATH="./node_modules/.bin:$PATH"

# java stuff http://www.jenv.be/
if which jenv > /dev/null; then eval "$(jenv init -)"; fi

# perl path stuff
# ~/perl5/
export -- PERL_LOCAL_LIB_ROOT="/Users/andxyz/perl5:$PERL_LOCAL_LIB_ROOT";
export -- PERL_MB_OPT="--install_base "/Users/andxyz/perl5"";
export -- PERL_MM_OPT="INSTALL_BASE=/Users/andxyz/perl5";
export -- PERL5LIB="/Users/andxyz/perl5/lib/perl5:$PERL5LIB";
export -- PATH="/Users/andxyz/perl5/bin:/Users/andxyz/perl5/perlbrew/bin::$PATH";

# php stuff
which php54 >> /dev/null 2>&1 &&
export -- PATH="$(brew --prefix homebrew/php/php54)/bin:$PATH"
which php55 >> /dev/null 2>&1 &&
export -- PATH="$(brew --prefix homebrew/php/php55)/bin:$PATH"
which php56 >> /dev/null 2>&1 &&
export -- PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"

# python path stuff
test -f "/usr/local/lib/python" &&
export -- PYTHONPATH=/usr/local/lib/python:$PYTHONPATH

# rbenv stuff https://github.com/sstephenson/rbenv#readme
# note currently I use a "be=bundle exec" alias
test -d $HOME/.rbenv/bin &&
export -- PATH="$HOME/.rbenv/bin:$PATH" &&
eval "$(rbenv init -)"

# java sdkman http://sdkman.io/
export SDKMAN_DIR="/Users/andxyz/.sdkman"
[[ -s "/Users/andxyz/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/andxyz/.sdkman/bin/sdkman-init.sh"

echo \
"""export -- PATH=
$PATH"""
