#!/usr/bin/bash

set -eufo pipefail

# Sept 2020

brew upgrade 'automake'
brew upgrade 'awscli'
brew upgrade 'bash-completion@2'
brew upgrade 'bat'
brew upgrade 'binutils'
brew upgrade 'cmake'
brew upgrade 'cppcheck'
brew upgrade 'dash'
brew upgrade 'django-completion'
brew upgrade 'fpp'
brew upgrade 'fzf'
brew upgrade 'gcc'
brew upgrade 'git'
brew upgrade 'git-quick-stats'
brew upgrade 'grep'
brew upgrade 'highlight'
brew upgrade 'htop'
brew upgrade 'httpie'
brew upgrade 'jenv'
brew upgrade 'llvm'
brew upgrade 'macvim'
brew upgrade 'mas'
brew upgrade 'muesli/tap/duf'
brew upgrade 'parallel'
brew upgrade 'pgcli'
brew upgrade 'rake-completion'
brew upgrade 'redis'
brew upgrade 'rs/tap/curlie'
brew upgrade 'tika'
brew upgrade 'vagrant-completion'
brew upgrade 'youtube-dl'

# Nov 2020

brew upgrade 'awscli'
brew upgrade 'django-completion'
brew upgrade 'ffmpeg'
brew upgrade 'fzf'
brew upgrade 'git'
brew upgrade 'git-lfs'
brew upgrade 'grep'
brew upgrade 'muesli/tap/duf'
brew upgrade 'nomad'
brew upgrade 'rbspy'
brew upgrade 'redis'
brew upgrade 'rs/tap/curlie'
brew upgrade 'tmuxinator-completion'
brew upgrade 'unrar'
brew upgrade 'vagrant-completion'
brew upgrade 'youtube-dl'
