#!/usr/bin/env bash
$include /etc/inputrc
$include /usr/local/etc/inputrc

### Notes on possible settings
## see https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File-Syntax.html
## bell-style - Possible values are audible (the default), visible, or none.
## completion-ignore-case
## convert-meta - If on (the default), characters are converted to the ASC seven bit character set.
## disable-completion
## editing-mode - May be set to emacs or vi see https://github.com/prograhamer/dotfiles/blob/e5073bb78f1762b6172dc091f2e65d5bac9c35cb/.inputrc
## enable-keyboard
## expand-tilde
## input-meta - If set to on, eight bit input is enabled. If off (the default) it only passes seven bits of any character.

# for andxyz and zsh see https://github.com/andxyz/.dotfiles/blob/ff027cc6fac5d519deda3ba166968d1883f4246d/zsh/config_zsh#L39

set bell-style none

set show-all-if-ambiguous on
set completion-ignore-case on

# vi mode in everything that uses readline
# set -o vi
# set editing-mode vi
# set editing-mode emacs
# set keymap vi-command

# Can we be 8 bit clean? https://en.wikipedia.org/wiki/8-bit_clean
# see http://www.comptechdoc.org/os/linux/howlinuxworks/linux_hlkeyprogs.html
set input-meta on
set meta-flag on
set output-meta on
set convert-meta off
set enable-meta-key on

## The following sequences are used to help define keys:
#
## \C- = Control
## \M- = Meta
## \e = escape character
## \\ = backslach

# osx setup
# see http://superuser.com/questions/357355/how-can-i-get-controlleft-arrow-to-go-back-one-word-in-iterm2
# alt-left-arrow and alt-right-arrow for jumping to word-beginnings on the commandline

"\e[1;5D": backward-word
"\e[1;5C": forward-word
"\e[1;9D": backward-word
"\e[1;9C": forward-word

# "\e[1;9D":backward-word
# "\e[1;3D":backward-word
# "\e[1;5D":backward-word

# "\e[1;9C":forward-word
# "\e[1;5C":forward-word
# "\e[1;3C":forward-word

## use Ctrl <- and Ctrl -> for jumping to word-beginnings on the CL
# bindkey "^[[1;5D" backward-word
# bindkey "^[[1;5C" forward-word
#
## the same for alt-left-arrow and alt-right-arrow
# bindkey '^[[1;3D' backward-word
# bindkey '^[[1;3C' forward-word
#
## Delete key
# "\e[3~":delete-char
