#!/usr/bin/ruby

# https://github.com/cldwalker/hirb/issues/46#issuecomment-1870823
# Pry.config.print = proc do |output, value|
#   Hirb::View.view_or_page_output(value) || Pry::DEFAULT_PRINT.call(output, value)
# end
