#!/usr/bin/env bash
set -e
set -x

# man ctags
# https://manned.org/ctags-exuberant/05e759a0

PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT

git ls-files | \
ctags -R --tag-relative --languages=+ruby,-javascript,sql --exclude=.git -f"$dir/$$.tags"

mv "$dir/$$.tags" "$dir/tags"
