#!/usr/bin/env bash

set -e

### php
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap josegonzalez/homebrew-php
#### you should read the following for php
##### `brew options php54`
##### `brew install php54`
##### `brew options php55`
##### `brew info php55`
##### `browser http://justinhileman.info/article/reinstalling-php-on-mac-os-x/`
##### `browser blog.frd.mn/install-nginx-php-fpm-mysql-and-phpmyadmin-on-os-x-mavericks-using-homebrew/`
brew install php54 --homebrew-apxs --with-fpm --with-homebrew-openssl --with-mysql --with-pgsql 
brew install php55 --homebrew-apxs --with-fpm --with-homebrew-openssl --with-mysql --with-pgsql 

### php addons to the addons
##### brew options imagemagick
brew install 'imagemagick'
##### brew info imagemagick

exit 0
