#!/usr/bin/env bash

set -e

## see https://github.com/sstephenson/rbenv/wiki/_pages
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv &&
export PATH="$HOME/.rbenv/bin:$PATH" &&
eval "$(rbenv init -)"

# optional, but recommended:
brew install openssl libyaml readline

## plugins ahoy, see https://github.com/sstephenson/rbenv/wiki/Plugins
mkdir $HOME/.rbenv/plugins/ &&
git clone https://github.com/sstephenson/ruby-build.git $HOME/.rbenv/plugins/ruby-build &&
git clone https://github.com/rkh/rbenv-update.git $HOME/.rbenv/plugins/rbenv-update &&
git clone https://github.com/sstephenson/rbenv-gem-rehash.git $HOME/.rbenv/plugins/rbenv-gem-rehash &&
git clone https://github.com/sstephenson/rbenv-default-gems.git $HOME/.rbenv/plugins/rbenv-default-gems

ls "$(rbenv root)"/plugins

## prepare ruby-build, see https://github.com/sstephenson/ruby-build/wiki
cd "$(rbenv root)"/plugins/ruby-build && git pull
cd $HOME

# required for building Ruby <= 1.9.3-p0:
# brew tap homebrew/dupes && brew install apple-gcc42

## install some rubies
#
# rbenv install -l
# rbenv install 1.8.7-p375
# rbenv install 1.9.3-p448
# rbenv install 2.0.0-p481
rbenv install 1.9.3-p547
rbenv install 2.1.2
rbenv install 2.2.0
#rbenv install jruby-1.7.16.1

## set my default rubies for new shells
#
# rbenv shell 1.9.3-p547
# rbenv global 1.9.3-p547
rbenv shell 2.2.0
rbenv global 2.2.0

## show off my new whiz bangs! you guys! We gots whiz-bangs!
rbenv rehash
rbenv versions

## example use cases of some of our plugins
# rbenv update
# echo "bundler\npry\nbcat" >> $HOME/.rbenv/default-gems
# rbenv whence bundler

exit 0
