#!/usr/bin/env bash

set -e

## see https://github.com/sstephenson/rbenv/wiki/_pages
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv &&
export PATH="$HOME/.rbenv/bin:$PATH" &&
eval "$(rbenv init -)"

# optional, but recommended:
brew install openssl libyaml readline

## plugins ahoy, see https://github.com/sstephenson/rbenv/wiki/Plugins
mkdir $HOME/.rbenv/plugins/
git clone https://github.com/sstephenson/ruby-build.git $HOME/.rbenv/plugins/ruby-build
git clone https://github.com/sstephenson/rbenv-gem-rehash.git $HOME/.rbenv/plugins/rbenv-gem-rehash
git clone https://github.com/rkh/rbenv-whatis.git $HOME/.rbenv/plugins/rbenv-whatis
git clone git://github.com/tpope/rbenv-communal-gems.git $HOME/.rbenv/plugins/rbenv-communal-gems
git clone https://github.com/sstephenson/rbenv-default-gems.git $HOME/.rbenv/plugins/rbenv-default-gems
git clone https://github.com/rkh/rbenv-update.git $HOME/.rbenv/plugins/rbenv-update
git clone https://github.com/chriseppstein/rbenv-each.git $HOME/.rbenv/plugins/rbenv-each

## readline fixie, I loves my fixie
brew install readline && git clone git://github.com/tpope/rbenv-readline.git $HOME/.rbenv/plugins/rbenv-readline
ls "$(rbenv root)"/plugins

## prepare ruby-build, see https://github.com/sstephenson/ruby-build/wiki
cd "$(rbenv root)"/plugins/ruby-build && git pull
cd $HOME

# required for building Ruby <= 1.9.3-p0:
# brew tap homebrew/dupes && brew install apple-gcc42

## install some rubies 
#
# rbenv install -l
# rbenv install 1.8.7-p375
# rbenv install 1.9.3-p448
# rbenv install 1.9.3-p545
# rbenv install 2.1.0
rbenv install 2.1.1
## set my default rubies for new shells
#
rbenv shell 1.9.3-p448
rbenv global 1.9.3-p448
# rbenv shell 1.9.3-p545
# rbenv global 1.9.3-p545

## show off my new whiz bangs! you guys! We gots whiz-bangs!
rbenv rehash
rbenv versions

## example use cases
# subl -n $HOME/.rbenv/default-gems
# rbenv whence rackup

exit 0
