#!/usr/bin/env zsh

function cdff_show_folder_name { osascript -e 'tell application "Finder"'\
 -e "if (${1-1} <= (count Finder windows)) then"\
 -e "get POSIX path of (target of window ${1-1} as alias)"\
 -e 'else' -e 'get POSIX path of (desktop as alias)'\
 -e 'end if' -e 'end tell'; };\

# cd to the front most finder window
function cdff { cd "$(cdff_show_folder_name $@)"; echo "${PWD}" };
