#!/usr/bin/env zsh

function ddockerinit_docker_machine {
  set -x
  docker-machine start
  eval $(docker-machine env default)
  export -- DOCKER_IP=$(docker-machine ip default)
  set +x
}

export -- DOCKER_IP=0.0.0.0
