#!/usr/bin/env zsh

autoload -U compinit
compinit

# brew info zsh-completions
# ls /usr/local/share/zsh-completions
# rm -f ~/.zcompdump; compinit
fpath=(/usr/local/share/zsh-completions $fpath)

# matches case insensitive for lowercase
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# pasting with tabs doesn't perform completion
zstyle ':completion:*' insert-tab pending
