#!/usr/bin/env zsh

# allow bash style comments
setopt interactivecomments

## zsh function nonsense
fpath=(~/.zsh/functions $fpath)
autoload -U ~/.zsh/functions/*(:t)

## fancy git prompt on my local machine using a zsh function
if [[ -n $SSH_CONNECTION ]]; then
  export -- PS1=$'%m:%3~$(git_info_for_prompt)\n$ '
else
  export -- PS1=$'%3~$(git_info_for_prompt)\n$ '
fi

## shell specific history
export -- HISTFILE=$HOME/.zsh_history

## force some ENV configs
setopt NO_BG_NICE # don't nice background tasks
setopt NO_HUP
setopt NO_LIST_BEEP
setopt LOCAL_OPTIONS # allow functions to have local options
setopt LOCAL_TRAPS # allow functions to have local traps
setopt HIST_VERIFY
setopt SHARE_HISTORY # share history between sessions ???
setopt EXTENDED_HISTORY # add timestamps to history
setopt PROMPT_SUBST
setopt CORRECT
setopt COMPLETE_IN_WORD
setopt IGNORE_EOF

setopt APPEND_HISTORY # adds history
setopt INC_APPEND_HISTORY SHARE_HISTORY  # adds history incrementally and share it across sessions
setopt HIST_IGNORE_ALL_DUPS  # don't record dupes in history
setopt HIST_REDUCE_BLANKS

## bind some key fixes for keyboards

zle -N newtab

bindkey -e
bindkey '^R' history-incremental-pattern-search-backward

## see http://superuser.com/questions/357355/how-can-i-get-controlleft-arrow-to-go-back-one-word-in-iterm2

## ctrl-left ctrl-right
bindkey "\e[1;5C" forward-word
bindkey "\e[1;5D" backward-word

## alt-left alt-right
bindkey '^[[1;9C' forward-word
bindkey '^[[1;9D' backward-word

# see http://stackoverflow.com/questions/890620/unable-to-have-bash-like-c-x-e-in-zsh
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# bindkey '^[^[[D' backward-word
# bindkey '^[^[[C' forward-word
# bindkey '^[[5D' beginning-of-line
# bindkey '^[[5C' end-of-line
# bindkey '^[[3~' delete-char
# bindkey '^[^N' newtab
# bindkey '^?' backward-delete-char
