#!/usr/bin/env zsh

# brew info zsh-completions
#
# ls /usr/local/share/zsh-completions
# chmod -R go-w '/usr/local/share/zsh'
# rm -f ~/.zcompdump; compinit

if type brew &>/dev/null; then
  export FPATH="$(brew --prefix)"/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi
# compaudit
#
# sudo chmod -R g-w /usr/local/share/zsh/site-functions
# sudo chmod -R g-w /usr/local/share/zsh
# sudo chmod -R g-w /usr/local/share/
#
#
#

zstyle ':completion:*' menu select # Style of completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # matches case insensitive for lowercase
zstyle ':completion:*' insert-tab pending # pasting with tabs doesn't perform completion
# source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" # Highlight syntax
