#!/usr/bin/env zsh

setopt INTERACTIVECOMMENTS # allow bash style comments

# http://superuser.com/questions/71857/change-the-output-format-of-zshs-time
disable -r time       # disable shell reserved word
alias time='time -p ' # -p for POSIX output

## zsh function nonsense
fpath=(~/.zsh/functions $fpath)
autoload -U ~/.zsh/functions/*(:t)

## fancy git prompt on my local machine using a zsh function
if [[ -n $SSH_CONNECTION ]]; then
  export -- PS1=$'%m:%3~$(git_info_for_prompt)\n$ '
else
  export -- PS1=$'%3~$(git_info_for_prompt)\n$ '
fi

## force some ENV configs
setopt NO_BEEP
setopt NO_BG_NICE # don't nice background tasks
setopt NO_HUP
setopt NO_LIST_BEEP
setopt LOCAL_OPTIONS # allow functions to have local options
setopt LOCAL_TRAPS # allow functions to have local traps
setopt HIST_VERIFY
setopt PROMPT_SUBST
setopt CORRECT
setopt COMPLETE_IN_WORD
setopt IGNORE_EOF

## shell specific history
export -- HISTFILE=$HOME/.zsh_history

setopt APPEND_HISTORY # adds history
setopt EXTENDED_HISTORY # add timestamps to history
setopt INC_APPEND_HISTORY # adds history incrementally
setopt SHARE_HISTORY # share history between sessions ???
setopt HIST_IGNORE_ALL_DUPS  # don't record dupes in history
setopt HIST_REDUCE_BLANKS

## bind some key fixes for keyboards

zle -N newtab

bindkey -e
bindkey '^R' history-incremental-pattern-search-backward

## see http://superuser.com/questions/357355/how-can-i-get-controlleft-arrow-to-go-back-one-word-in-iterm2

## ctrl-left ctrl-right
bindkey "\e[1;5C" forward-word
bindkey "\e[1;5D" backward-word

## alt-left alt-right
bindkey '^[[1;9C' forward-word
bindkey '^[[1;9D' backward-word

# see http://stackoverflow.com/questions/890620/unable-to-have-bash-like-c-x-e-in-zsh
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# bindkey '^[^[[D' backward-word
# bindkey '^[^[[C' forward-word
# bindkey '^[[5D' beginning-of-line
# bindkey '^[[5C' end-of-line
# bindkey '^[[3~' delete-char
# bindkey '^[^N' newtab
# bindkey '^?' backward-delete-char

# Colorize man pages, yoink! https://github.com/Nitrodist/dotfiles/commit/d8f19be5c5ebcd5767eb91a776b5ce23f73a19ab
man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}

alias rezsh='source ${HOME}/.zshrc'

# for interactive to have access to languages
#source_golang110_path
source_node_env
source_ruby_env
