#!/usr/bin/env bash
# set -x
# set -e

## shell specific history
export -- HISTFILE=$HOME/.bash_history

# use the homebrew bash 4+ completions if they exist
if [ -f /usr/local/share/bash-completion/bash_completion ]; then
  source /usr/local/share/bash-completion/bash_completion
fi

# carapace-bin dance https://github.com/carapace-sh/carapace-bin?tab=readme-ov-file#getting-started
# see https://carapace-sh.github.io/carapace-bin/setup.html#bash
if type carapace &>/dev/null; then
  export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense' # optional
  source <(carapace _carapace)
fi;

## http://git-prompt.sh/
## fancy git prompt on my local machine using a function
# if [[ -n $SSH_CONNECTION ]]; then
#   export -- PS1='\h \w$(__git_ps1 " (%s)")\n\$ '
# else
#   export -- PS1='\w$(__git_ps1 " (%s)")\n\$ '
# fi

# pull in iterm2 shell integrations
if [[ -e "${HOME}/.iterm2_shell_integration.bash" ]]; then
  source "${HOME}/.iterm2_shell_integration.bash"
fi
