#!/usr/bin/env bash

## shell specific history
export -- HISTFILE=$HOME/.bash_history

# use the homebrew git prompt script else use and old one
if test -f /usr/local/etc/bash_completion.d/git-prompt.sh; then
  source /usr/local/etc/bash_completion.d/git-prompt.sh
else
  source $HOME/.git-prompt.sh
fi

## http://git-prompt.sh/
## fancy git prompt on my local machine using a function
if [[ -n $SSH_CONNECTION ]]; then
  export -- PS1='\h \w$(__git_ps1 " (%s)")\n\$ '
else
  export -- PS1='\w$(__git_ps1 " (%s)")\n\$ '
fi
